# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Build at 00:00 on every 3rd day-of-month.
  schedule:
    - cron: "0 0 */3 * *"
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cncra2yr"
  cncra2yr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a single-line script
        run: bash deploy.sh stable

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: cncra2yr-continuous-x86_64.AppImage
          path: 'dist'

  # This workflow contains a single job called "cncra2yr-wp"
  cncra2yr-wp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a single-line script
        run: xvfb-run --server-args="-screen 0 1024x768x24" bash deploy.sh stablewp

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: cncra2yr-continuous-wp-x86_64.AppImage
          path: 'dist'

  release-stable:
    needs: [cncra2yr]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: cncra2yr-continuous-x86_64.AppImage

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: cncra2yr stable
          automatic_release_tag: stable
          prerelease: false
          draft: false
          files: |
            cncra2yr-continuous-x86_64.AppImage
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  release-stable-wp:
    needs: [cncra2yr-wp]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: cncra2yr-continuous-wp-x86_64.AppImage

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: cncra2yr stable with wineprefix
          automatic_release_tag: stable-wp
          prerelease: false
          draft: false
          files: |
            cncra2yr-continuous-wp-x86_64.AppImage
          repo_token: ${{ secrets.GITHUB_TOKEN }}
